#ifndef _AUTHENTICATION_PRIVATE_H
#define _AUTHENTICATION_PRIVATE_H

typedef enum
{
    AUTH_STATE_IDLE,
    AUTH_STATE_AWAITING_INPUT,
    AUTH_STATE_VALIDATING,
    AUTH_STATE_LOCKED_OUT
} AUTH_State_t;

#endif /*_AUTHENTICATION_PRIVATE_H*/
